### ISSUE TITLE
Cannot read properties of undefined (reading '$$')

### ISSUE THREAD

**Issue by lukaszpolowczyk** [rafalou38/svelte-preview#10]
SvelteKit.

This:
```svelte
<!-- /previews/ButPole.svelte -->
<script>
	import Button from "$lib/Button.svelte"
</script>

<Button de="dd"/>
```

```svelte
<!-- /src/lib/Button.svelte -->
<button>aaa</button>
```

Error:

```
TypeError: Cannot read properties of undefined (reading '$$')
    at init (/media/WebDev/svelte project/node_modules/svelte/internal/index.mjs:1886:50)
    at new Component (/media/svelte project/src/lib/Button.svelte:35:3)
    at create_fragment (/media/WebDevsvelte project/previews/ButPole.svelte:19:11)
    at init (/media/WebDev/svelte project/node_modules/svelte/internal/index.mjs:1906:37)
    at new Component (/media/WebDev/svelte project/previews/ButPole.svelte:48:3)
    at /media/WebDev/svelte project/previews/ButPole.svelte:52:5```

**Comment by rafalou38** [comment]
Hi, I made some changes to the code, can you try this dev build and tell me if it fixes your issue?

To install: 
1. uninstall `svelte-preview`
2. extract the archive [svelte-preview-2.5.5-dev.zip](https://github.com/rafalou38/svelte-preview/files/9409712/svelte-preview-2.5.5-dev.zip)
3. run this command `workbench.extensions.action.installVSIX` from the command palette 
4. choose the file extracted from the archive.

**Comment by lukaszpolowczyk** [comment]
@rafalou38 I checked and it works, no errors are visible:
![obraz](https://user-images.githubusercontent.com/16800535/186415979-bda7deda-b1fa-4b24-bdcd-50ec979b6644.png)

**Comment by rafalou38** [comment]
Nice!
I'm going to push the update to the marketplace,
You can uninstall the version I gave you and download the public one if you want to receive future updates.
