### ISSUE TITLE
An error that SHOULD NOT block the preview rendering, but does

### ISSUE THREAD

**Issue by lukaszpolowczyk** [rafalou38/svelte-preview#11]
Such an error appears:
```
unused-export-let Component has unused export property 'sei'. If it is for external reference only, please consider using `export const sei` [4:19]
17: export
18: /** @type {number} */
19: let sei = "z"; // export /** @type {number} */ let firstColor;
        ^
20: // export /** @type {number} */ let secondColor;
21: 
```
And because of this, the preview does not display at all.

In my opinion, this is an exaggeration, this error may display, but it should not block the preview display.

This error should be ignored, because such a page can be rendered normally in the preview anyway.

Perhaps there are more errors of this type that block the preview, and they shouldn't?

**Comment by lukaszpolowczyk** [comment]
Such code:

```svelte
{#each [...gen(44, 96)] as item}
  {@const title = item.toString()}
  <div class="tick-container" {title}>
    <div class="tick">
      
    </div>
  </div>
{/each}
```

Causes such an error:

```
Unexpected character '@' [3:15]
```

It's all about the line:
```svelte
{@const title = item.toString()}
```

And it shouldn't, because it's normal SvelteJS code.

**Comment by rafalou38** [comment]
Sorry for the delay. I've been very busy lately.

Everything should be fixed now, just wait for the update.
