### ISSUE TITLE
TypeError: Failed to resolve module specifier "local-package/viewing/test.js". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by lukaszpolowczyk** [rafalou38/svelte-preview#12]
I use a method to load node packages, from another disk location, the same device (local testing).

In `package.json` it looks like this:

```json
{
	"dependencies": {
		"local-package": "file:../local-package"
	}
}
```

And it is used like this:
```javascript
import { testIn } from "local-package/viewing/test.js";
```

Such a package is installed like this:
```bash
  npm install --save /path/to/package
```

The package is a folder.

When I test the import component from such a package, in svelte-preview, such an error appears:
```
TypeError: Failed to resolve module specifier "local-package/viewing/test.js". Relative references must start with either "/", "./", or "../".
```

Please add support for such packages and such import from local package dependencies.

**Comment by rafalou38** [comment]
Sorry but I don't plan to support this functionality, it would imply a lot of work and would probably not be used that much.
If you need it you can use a classic svelte compiler with hot reloading.

**Comment by lukaszpolowczyk** [comment]
@rafalou38 I'm currently using it, so it's a big detriment to me.

It's easier than creating a package, sending it to the repository, etc., and so on, over and over again, with each update.


GREAT BIG HARM.
