### ISSUE TITLE
Add an extension setting so that the button panel does not display at all

### ISSUE THREAD

**Issue by lukaszpolowczyk** [rafalou38/svelte-preview#13]
The most annoying thing - the panel with buttons.
It displays and SHOWS the COMPONENT. Although I don't use this panel at all.
![obraz](https://user-images.githubusercontent.com/16800535/187511999-ec6836e2-76d3-4c10-8c97-9e77ced21d5d.png)

Please add a setting for the VSCode extension so that this panel doesn't show up at all by default.
Please do so very much!

**Comment by rafalou38** [comment]
The button on the top right to hide it is not enough?

**Comment by lukaszpolowczyk** [comment]
@rafalou38 No.
I often close and open the preview because I'm not sure if the preview is stuck.
(Check out the issue I wrote here. and yet another one has come up, which I'll describe in a moment.)

And then I have to keep clicking that button in the upper right corner.

Besides, sometimes I want to see literally every pixel, and this button also obstructs.

**Comment by rafalou38** [comment]
Sorry for the huge delay, I didn't have time and did not feel the urge to implement this feature.
It should now be available under the next update.
