### ISSUE TITLE
"Module not found: svelte/internal" when node_modules in project but svelte is not installed

### ISSUE THREAD

**Issue by greenmoonslug** [rafalou38/svelte-preview#14]
When I click the Svelte-preview icon on the top of .svelte file's column, new column appears, but no web page is shown (just settings appear on above).
And an error `module not found: svelte/internal` is always there.
![scrs2022-09-22 13 30 09](https://user-images.githubusercontent.com/6505051/191659811-cb357b72-d18a-490f-b3fd-d824ef880a01.png)

Does it require some files or something?

- Mac mini (M1, 2020) / MacOS 12.6
- Visual Studio Code 1.71.2

**Comment by rafalou38** [comment]
Svelte internal is the runtime of svelte it normally searches for it in node_modules and fallback to the one found in the extension directory, this error should not happen 😅

Do you have svelte installed in this project?
If so, could you share your package lock


Can you share the svelte code you have?

**Comment by greenmoonslug** [comment]
I'm sorry for my misunderstanding.
I'm looking for some svelte file previewer which can run without dependency of each projects, and I thought this extension is.
Thank you for your mention.

**Comment by rafalou38** [comment]
The extension is supposed to work without dependencies

Example:
![image](https://user-images.githubusercontent.com/58974586/192090926-35d09150-cd2c-46ac-9ed5-96c49020ffe7.png)

but in your case it does not work and I don't know why 🤨

**Comment by rafalou38** [comment]
I see the issue, you have node_modules but svelte is not installed in them,
The extensions use the integrated one only when you don't have node_modules
I'm going to make an update to make it work

**Comment by greenmoonslug** [comment]
I'm so glad to hear that the extension supports what I want.
Though, in the first of this issue, there's only the .svelte file and not node_modules on its directory ( and I opened the directory as a workspace on VSCode when I tested that ) .

Here is 3 more cases which I have tested following your mention;
- **Setting VSCode as "No Folder Opened"**: Nothing happened, but same error `module not found: svelte/internal` occurs.
- **Setting workspace with empty node_modules**: Same error occurs.
- **Setting workspace with node_modules and svelte modules**: It works.

**Comment by rafalou38** [comment]
Can you checked if you don't have some node_modules in a parent folder, that's a common issue.

Can you also share the code that causes the issue?

The issue might also just be Mac OS, i haven't tested the extension with this OS.

**Comment by rafalou38** [comment]
That should be fixed now, the extension doesn't rely on the svelte version from the user at all and uses the extension (latest) one instead.

**Comment by greenmoonslug** [comment]
I've tested on MacOS now, it does work!!
This feature really helps partial coding, and component-oriented development with svelte.😎 Thank you for your considering and works!
