### ISSUE TITLE
Use latest Tailwind cdn

### ISSUE THREAD

**Issue by danxcraig** [rafalou38/svelte-preview#15]
**Is your feature request related to a problem? Please describe.**
When adding Tailwind from settings, 2.2.19 is used (https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css)

Tailwind is now on 3.3.1 so this means some classes do not render as expected (for example stroke and fill on SVGs).

**Describe the solution you'd like**
Option to use the Play CDN (https://tailwindcss.com/docs/installation/play-cdn) instead.

**Comment by rafalou38** [comment]
External scripts are not yet supported by the extension, I'm going to add them.
Until then, you can just get the latest CSS CDN.

**Comment by rafalou38** [comment]
Done !

I also added daisy UI to the buttons, do you have recommendation of other styles or scripts I can add ?
![image](https://user-images.githubusercontent.com/58974586/232489077-d513aad0-4fb8-4e2b-99b3-f3ad2983bf65.png)

PS: The update should be available later today.

**Comment by danxcraig** [comment]
That was quick! Super duper.

Re styles and ui libraries, Flowbite and Skeleton are the other two I'm aware of which are in a lot of use if that helps.
