### ISSUE TITLE
Module is not found for $app imports 

### ISSUE THREAD

**Issue by danxcraig** [rafalou38/svelte-preview#16]
**Describe the bug**
When using $app imports, console complains that the module is not found.

**To Reproduce**
Try to import any module from app. Example:

- import { enhance } from "$app/forms"
- import { browser, building, dev, version } from '$app/environment';

**Expected behavior**
module imports successfully

**Logs**
_module not found: $app/forms [0:0]_
_module not found: $app/environment [0:0]_

**Version:**
v2.6.2

**Additional context**

- $app/forms works / compiles fine on npm run dev and build
- Using sveltekit@latest
- $app/forms & $app/environment links to the module declaration in ambient.d.ts

**Comment by rafalou38** [comment]
I fixed the $app import but I still cannot get it to work completely.
Some sveltekit functions rely on __sveltekit/paths wich exports himself causing a circular dependency.
https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/app/paths.js
So you will be able to import it but it will cause a circular dependency error.

Svelte-kit seem to be doing some strange things with theses imports and it won't work outside of the svelte-kit env.
