### ISSUE TITLE
Typescript v5.x breaks

### ISSUE THREAD

**Issue by FractalHQ** [rafalou38/svelte-preview#17]
**Describe the bug**
When trying to run from a project with Typescript v5 and `moduleResolution: "bundler"` set, `svelte-preview` errors:

```
error TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node16', 'nodenext'.
error TS5023: Unknown compiler option 'verbatimModuleSyntax'.
```

**Version:**
2.6.2

**Additional context**
I could be misdiagnosing the problem, but hopefully the fix is as simple as bumping an internal TS version!

**Comment by Somberland** [comment]
Also happens to me including the `ignoreDeprecations `-error:

```
error TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node16', 'nodenext'.
error TS5023: Unknown compiler option 'verbatimModuleSyntax'.
error TS5023: Unknown compiler option 'ignoreDeprecations'.
```

**Comment by rafalou38** [comment]
Sorry for the delay, I've been really busy lately
It should all be fixed on the next release 👍
