### ISSUE TITLE
Publish to VSX-Registry

### ISSUE THREAD

**Issue by mmailaender** [rafalou38/svelte-preview#18]
All VScode users that use a forked VScode version (e.g. [Gitpod](https://www.gitpod.io/)) can only use Extensions from the [VSX-registry.](https://open-vsx.org/)

Could you please upload your extension also to VSX?

There is a guide: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
And there is also a Github Action that uploads to MS Marketplace and VSX-registry at the same time: https://github.com/HaaLeo/publish-vscode-extension#readme

**Comment by rafalou38** [comment]
Now available, in open vsx: https://open-vsx.org/extension/RafaelMartinez/svelte-preview
