### ISSUE TITLE
Component preview showing empty page

### ISSUE THREAD

**Issue by mmailaender** [rafalou38/svelte-preview#19]
**Describe the bug**
Trying to preview a component shows only a white page:
![image](https://github.com/rafalou38/svelte-preview/assets/87228994/acea42de-6c09-42a4-86ed-f1c89b1b148c)

**To Reproduce**
1. Go to [Gitpod](https://gitpod.io/?autostart=true#https://github.com/mmailaender/svelte-preview-bug/blob/main/src/routes/%2Bpage.svelte)
2. Click on 'Svelte Preivew'
![image](https://github.com/rafalou38/svelte-preview/assets/87228994/f61c1503-7ad6-49f5-859a-dd5915aac406)

3. See error (Nothing is shown)

**Expected behavior**
The component will be previewed

**Logs**
Run the command `workbench.action.webview.openDeveloperTools` and make a screenshoot/pastebin of the console content
![image](https://github.com/rafalou38/svelte-preview/assets/87228994/ffcbb00f-de79-4cb1-98af-ac5608d9a039)

**Version:**
2.7.0

**Comment by rafalou38** [comment]
I have located the issue.
In a normal svelte-preview installation (I have not designed it to work on web) messages going to the webview (code updates to preview) have the "vscode-webview:" prefix in the event origin. 
This is used to verify the authenticity of the event (for security purposes).
So, to fix this issue, I must find if there is another way or just remove this security, I don't really know if it is really needed.
I will investigate further.

**Comment by rafalou38** [comment]
I have resolved the issue, the preview should now appear in theses web-based versions.
However, svelte-preview does not support postcss, so this specific example you gave will not work like it is.

If you really want postcss you can make a new issue, but I have looked at it and don't think I'll be able to implement it.
