### ISSUE TITLE
TailwindCSS not working

### ISSUE THREAD

**Issue by nikosgpet** [rafalou38/svelte-preview#4]
**Describe the bug**
I am currently running a fresh install of SvelteKit with TailwindCSS using postcss in the preprocessing step. Tailwind styles do not seem to be taken into consideration by Svelte preview.

**Version:**
`v2.3.1`

**Additional context**
This is the content of my `svelte.config.js`

```js
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: preprocess({
    postcss: {},
  }),
  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte',
    vite: () => ({
      cacheDir: ".vite"
    })
  },
};

export default config;
```

`postcss.config.cjs`
```js
module.exports = {
  plugins: {
    autoprefixer: {},
    'postcss-import': {},
    'tailwindcss/nesting': {},
    'tailwindcss': { config: './tailwind.config.cjs' },
  },
}

```

**Comment by brandonmcconnell** [comment]
If this is still an issue, I think it is rather important. I too would like to see this resolved.

**Comment by rafalou38** [comment]
![image](https://user-images.githubusercontent.com/58974586/156882161-a029c885-83c3-472d-b271-9f8df8dffc83.png)
You can load precompiled tailwindcss like this, is it not working?

**Comment by rafalou38** [comment]
Closing as it should be working now
