### ISSUE TITLE
How activate

### ISSUE THREAD

**Issue by silfar** [rafalou38/svelte-preview#6]
Hello, it's actually a question of mine, I didn't find how to activate the extension.
I tried CTRL+SHIFT+P but nothing related to the extension appeared.

**Comment by rafalou38** [comment]
Did you open a svelte file before?
In the command palette (CTPL+SHIFT+p) you should find the command `svelte-preview: preview component`
You can also open the preview by right clicking in the editor and clicking on Preview component or by pressing on the svelte logo in the top left.

**Comment by rafalou38** [comment]
I'm closing this issues, if you're still having troubles, feel free to reopen it.
