### ISSUE TITLE
Add ability to process compound components 

### ISSUE THREAD

**Issue by Mopholo** [rafalou38/svelte-preview#8]
**Is your feature request related to a problem? Please describe.**
This seems to work in simple components with no dependencies but doesn't understand how to bring in other components, at least when in svelte kit, so maybe it just needs support for that? 

The error message returned when I tried to view a parent container component 
module not found: $lib/actionBarHorizontal/actionBarHorizontal.svelte 

**Describe the solution you'd like**
Recognize sveltekit's $lib and or allow other required components to be loaded

**Comment by rafalou38** [comment]
I had already implemented that back in version [2.0](https://github.com/rafalou38/svelte-preview/blob/master/CHANGELOG.md#200) (9 months ago)
But for some reason, it does not work anymore. The format has probably changed and I need to re-adapt the code.

**Comment by rafalou38** [comment]
Ok, I think the issue comes from the fact that you're not using typescript, SveltePreview searches for paths inside of your tsconfig to use so it does not work without it
```json
"paths": {
	"$lib": ["lib"],
	"$lib/*": ["lib/*"]
}
```
If you want I can make it so that it searches $lib components inside of src/lib if you don't have a tsconfig
