### ISSUE TITLE
Preview gives out errors when using moduleSuffixes in tsconfig.json

### ISSUE THREAD

**Issue by AhmadAlaaAli** [rafalou38/svelte-preview#9]
**Describe the bug**

I have been using `moduleSuffixes` in my `tsconfig.json` but for some reason svelte-previews fails to compile.

**Screenshots**

![image](https://user-images.githubusercontent.com/110909069/185756725-dc8ef633-e39e-4e69-8384-a7e45615bd16.png)

**Version:**

`2.5.3`

**Additional context**

This is the content of my `Hello.svelte`
```svelte
<script lang="ts">
	console.log('Hello');
</script>
```
`tsconfig.json`
```json
{
  "compilerOptions": {
      "moduleSuffixes": ["", ".win"],
  }
}
```

**Comment by rafalou38** [comment]
The extension has an outdated typescript version, I'm going to update it.

**Comment by rafalou38** [comment]
I pushed a new version, you should not see that error anymore, but I don't think this feature (moduleSuffixes) is going to work with the extension.
